version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: avito_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}          # Установите пользователя для PostgreSQL
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Установите пароль для пользователя
      POSTGRES_DB: ${POSTGRES_DATABASE}        # Установите имя базы данных
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5430:5432"
  app:
    build: .
    environment:
      SERVER_ADDRESS: ${SERVER_ADDRESS}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST} 
      POSTGRES_PORT: ${POSTGRES_PORT} 
      POSTGRES_DATABASE: ${POSTGRES_DATABASE} 
      POSTGRES_CONN: ${POSTGRES_CONN}
    ports:
    -  8080:8080
    depends_on:
      - postgres